### ISSUE TITLE
Scanning stops at 2897 subdomains...

### ISSUE THREAD

**Issue by demajkel** [m0rtem/CloudFail#10]
as above, when I run cloudfail.py the whole process stops on subdomains scans!

I waited over 2 hours for the results but he was there! 'please wait...' he's still there!!! :)

**Comment by Elycin** [comment]
This is not a bug. 
A quick look at the subdomains file in the data folder shows there is exactly 2897 subdomains the script scans for.

**Comment by demajkel** [comment]
@Elycin thanks for that answer but i already knew that before ;) 
I understand that the script needs so much time to complete the scan?

**Comment by m0rtem** [comment]
There is an indication as to when the scan has finished, progress bars are a feature which I am currently working on and will be included in a later version.

**Comment by m0rtem** [comment]
This has now been included as of commit 325ccbd4a880f5f4d1c39f07b167aabdbecad4c9 thanks too: @bdoner

**Comment by demajkel** [comment]
hi! Thx for re. and progress bar ;) 
If somebody have similar problem with long time scanning, try to upgrade your distribution!
In my case that helped! ;)
