### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 5P4D3** [m0rtem/CloudFail#12]
![screenshot at 2017-07-08 19-11-50](https://user-images.githubusercontent.com/18681023/27984804-8ebd677a-6411-11e7-972a-0a176cf8346f.png)

**Comment by m0rtem** [comment]
are you using Python 3?

**Comment by 5P4D3** [comment]
Oh, okay.. when i tried the command python3 cloudfail.py this errors comes up..

![screenshot at 2017-07-09 12-57-21](https://user-images.githubusercontent.com/18681023/27991368-cb856672-64a6-11e7-855e-25922d46715e.png)

**Comment by m0rtem** [comment]
You need to install win_inet_pton on pip3 (for python3) pip3 install win_inet_pton

**Comment by 5P4D3** [comment]
Thanks to you.. it runs fine now.. you can close this as resolve now :D
