### ISSUE TITLE
invalid syntax : Any help please

### ISSUE THREAD

**Issue by sniper-ma** [m0rtem/CloudFail#13]
root@kali:~/Desktop/CloudFail# python cloudfail.py --target site.com
  File "cloudfail.py", line 23
    print(Style.NORMAL + "[" + datetimestr + "] " + data + Style.RESET_ALL,' ', end=end)
                                                                                   ^
SyntaxError: invalid syntax
root@kali:~/Desktop/CloudFail#

**Comment by m0rtem** [comment]
Hi mate

This is most likely due to invalid syntax with Python2, have you tried running with Python3?

**Comment by m0rtem** [comment]
Either setup Python3 or you can fork and remove the code thats invalid to Python3 (end=end)

**Comment by arbazkiraak** [comment]
To Solve the Issue  ! :100: 

sudo apt-get install python3-pip -y

/CloudFail# pip3 install -r requirements.txt

python3 cloudfail.py
