### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SOTUS** [m0rtem/CloudFail#15]
print(Style.NORMAL + "[" + datetimestr + "] " + data + Style.RESET_ALL,' ', end=end)
                                                                                   ^
SyntaxError: invalid syntax

**Comment by m0rtem** [comment]
have you tried running it with python 3 instead of 2?

**Comment by m0rtem** [comment]
print() is python3 where print"" is python 2, the print is a function in py3

**Comment by SOTUS** [comment]
How would i do that

**Comment by m0rtem** [comment]
You need to download and install Python3 and set it up alongside Python2.

There is a lot of help online e.g. https://stackoverflow.com/questions/341184/can-i-install-python-3-x-and-2-x-on-the-same-computer

I dont know what operating system you are using but it will be easier on linux...

**Comment by elizabeththecountess666** [comment]
thank you so very much!

**Comment by popo1337** [comment]
I'm having same issue and i'm using window's 10 can i follow the same procedure as you mention above ?

**Comment by m0rtem** [comment]
Hi @popo1337 yes that should still be fine if you're using windows 10. You just need python3 instead of python2. I may release patch which enables py2 to be used.

**Comment by popo1337** [comment]
Okay that would be fine :) 👍

**Comment by m0rtem** [comment]
Message on here if you need a hand with anything :)

**Comment by ripped12** [comment]
Please check picture what does it mean?

No Ipout file found ?
Unable to fetch CloudFlare subnet while tor is active ?

and its just sit there above picture the message you see.
so terminal I have type ctrl to stop the session to get me back to terminal prompt.

Can you please tell me why it aint getting the information. and why I'm getting these messages what you see in picture.

Thanks
![34650058-44248ae4-f3f5-11e7-8bbf-bbafde129f0b](https://user-images.githubusercontent.com/35172899/34650498-116d810c-f3fd-11e7-9250-416c71ae5107.png)

**Comment by m0rtem** [comment]
That error is due to the fact you are running Tor and cloudflare blocks requests from Tor nodes. Run without Tor  with --update to download all data files initially.

**Comment by bangkokhermetik** [comment]
Hi have the same issue "That error is due to the fact you are running Tor and cloudflare blocks requests from Tor nodes. Run without Tor with --update to download all data files initially." but i do not understand what you mean by "run without Tor, can you tell me how to update tor clearly please ;)
