### ISSUE TITLE
line fix

### ISSUE THREAD

**Issue by z3ro** [m0rtem/CloudFail#16]
please fix the following
with open('data/cf-subnet.txt', 'wb') as fd:
to get real path

**Comment by m0rtem** [comment]
will be included in next release, unless if you push a pull request with this change then I can merge? Thanks for the help!

**Comment by ripped12** [comment]
Please check picture what does it mean?

No Ipout file found ?
Unable to fetch CloudFlare subnet while tor is active ?

and its just sit there above picture the message you see.
so terminal I have type ctrl to stop the session to get me back to terminal prompt.

Can you please tell me why it aint getting the information. and why I'm getting these messages what you see in picture.

Thanks
![34650058-44248ae4-f3f5-11e7-8bbf-bbafde129f0b](https://user-images.githubusercontent.com/35172899/34650492-025bf630-f3fd-11e7-80ae-7d0a8cc91a9c.png)
