### ISSUE TITLE
ERROR ON SCRIPT PLEASE REVIEW - 7TH JANUARY 2018

### ISSUE THREAD

**Issue by ripped12** [m0rtem/CloudFail#21]
File "cloudfail.py", line 23
    print(Style.NORMAL + "[" + datetimestr + "] " + data + Style.RESET_ALL,' ', end=end)
                                                                                   ^
SyntaxError: invalid syntax

I used Kali Linux, and updated system and upgraded the system.
and updated the repositories. When using CloudFail, I get above error message.

Please review and fix. or guide what to do.

Thanks

**Comment by m0rtem** [comment]
Hi, you are using Python2, this script was optimised for Python3.

I have just pushed an update allowing compatibility for the print function syntax in Py2.

**Comment by ripped12** [comment]
Please check picture what does it mean?

No Ipout file found ?
Unable to fetch CloudFlare subnet while tor is active ?

and its just sit there above picture the message you see.
so terminal I have type ctrl to stop the session to get me back to terminal prompt.

Can you please tell me why it aint getting the information. and why I'm getting these messages what you see in picture.

Thanks
![34650058-44248ae4-f3f5-11e7-8bbf-bbafde129f0b](https://user-images.githubusercontent.com/35172899/34650481-df925158-f3fc-11e7-9562-1771c691cec8.png)
