### ISSUE TITLE
ERROR ON SCRIPT - 7TH JANUARY 2018 (PYTHON3)

### ISSUE THREAD

**Issue by ripped12** [m0rtem/CloudFail#22]
python3 cloudfail.py --target asexampleofanysiteputhere.com --tor

Traceback (most recent call last):
  File "cloudfail.py", line 9, in <module>
    import colorama
ImportError: No module named 'colorama'

Hi I'm using Kali Linux latest edition, updated system, upgraded the system, and all repositories up to date.

I submitted last error yesterday, due syntax, and was adviced to use python3
the above error I get when using "python3" instead of just "python" or "python2"

Please help or guide me to do next thing to get the script to work.

Thanks

**Comment by m0rtem** [comment]
I assume you have not read up on the error much nor looked through past questions already answered?

> ImportError: No module named

Literally means you dont have the module. Install it via:

> pip3 install requirements.txt

**Comment by ripped12** [comment]
![capture-20180107-214753](https://user-images.githubusercontent.com/35172899/34650058-44248ae4-f3f5-11e7-8bbf-bbafde129f0b.png)

Hi there I apologize I've downloaded and installed all packages just now.
and I tried it out. Ive blanked out my website address.

Please check picture what does it mean?

No Ipout file found ?
Unable to fetch CloudFlare subnet while tor is active ?

and its just sit there above picture the message you see.
so terminal I have type ctrl to stop the session to get me back to terminal prompt.

Can you please tell me why it aint getting the information. and why I'm getting these messages what you see in picture.

Thanks

**Comment by m0rtem** [comment]
That error is due to the fact you are running Tor and cloudflare blocks requests from Tor nodes. Run without Tor with --update to download all data files initially.
