### ISSUE TITLE
ImportError: No module named DNSDumpsterAPI

### ISSUE THREAD

**Issue by slrslr** [m0rtem/CloudFail#23]
Hello, i tried to install requirements on kali 4.6.0-kali1-686 and run the script, but got error. Here are steps:

$ wget https://github.com/m0rtem/CloudFail/raw/master/requirements.txt
$ wget https://github.com/m0rtem/CloudFail/raw/master/cloudfail.py
$ sudo apt-get install python3-pip

> The following NEW packages will be installed:
  gcc-7-base gcc-8-base libgfortran4 libpython3-dev libpython3.6 libpython3.6-dev libpython3.6-minimal libpython3.6-stdlib libssl1.1 libwebpmux3 python3-asn1crypto python3-cffi-backend python3-crypto
  python3-cryptography python3-dev python3-distutils python3-idna python3-keyring python3-keyrings.alt python3-lib2to3 python3-olefile python3-pip python3-secretstorage python3-setuptools python3-wheel
  python3.6 python3.6-dev python3.6-minimal

$ pip3 install -r requirements.txt

> Successfully installed beautifulsoup4-4.6.0 bs4-0.0.1 certifi-2017.4.17 chardet-3.0.4 colorama-0.3.9 idna-2.5 requests-2.18.1 urllib3-1.21.1 win-inet-pton-1.0.1

$ python cloudfail.py --target domain.here
Traceback (most recent call last):
  File "cloudfail.py", line 13, in <module>
    import win_inet_pton
ImportError: No module named win_inet_pton

$ pip install win_inet_pton
Collecting win_inet_pton
  Using cached win_inet_pton-1.0.1.tar.gz
Building wheels for collected packages: win-inet-pton
  Running setup.py bdist_wheel for win-inet-pton ... done
  Stored in directory: /home/me/.cache/pip/wheels/a5/7d/5d/5488e84ec3f64ed0691dfc8a926e6020423d8980cabe7b4410
Successfully built win-inet-pton
Installing collected packages: win-inet-pton
Successfully installed win-inet-pton-1.0.1

$ python cloudfail.py --target domain.here
Traceback (most recent call last):
  File "cloudfail.py", line 16, in <module>
    from DNSDumpsterAPI import DNSDumpsterAPI
ImportError: No module named DNSDumpsterAPI

$ pip install DNSDumpsterAPI
Collecting DNSDumpsterAPI
  Could not find a version that satisfies the requirement DNSDumpsterAPI (from versions: )
No matching distribution found for DNSDumpsterAPI

Please how to proceed?

**Comment by m0rtem** [comment]
Hi there

Please clone entire project as the DNSDumpster API is a module in itself, as in its a stand a lone file in the root of the project. So either clone whole project or wget this file here: https://github.com/m0rtem/CloudFail/blob/master/DNSDumpsterAPI.py

**Comment by slrslr** [comment]
Downloading that file into same directory like cloudfail.py worked:
cd /path/to/cloudfail
wget https://raw.githubusercontent.com/m0rtem/CloudFail/master/DNSDumpsterAPI.py

Now the error is:
[07:29:58] Updating CloudFlare subnet...  
Traceback (most recent call last):
  File "cloudfail.py", line 282, in <module>
    init(args.target)
  File "cloudfail.py", line 136, in init
    update()
  File "cloudfail.py", line 219, in update
    with open('data/cf-subnet.txt', 'wb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'data/cf-subnet.txt'

Can the README.md be updated to instruct one should also download data folder from the repo?

cd /path/to/cloudfail
mkdir data;cd data
wget https://raw.githubusercontent.com/m0rtem/CloudFail/master/data/subdomains.txt
wget https://raw.githubusercontent.com/m0rtem/CloudFail/master/data/cf-subnet.txt

**Comment by m0rtem** [comment]
I can update it, but honestly I do not see the point as normal install requires you to pull the whole repo, including the data dir. I don't see the point in downloading the files separately, unless you are working on a fork of the project.

May I ask why you are setting up the project this way?

**Comment by slrslr** [comment]
> normal install requires you to pull the whole repo ... why you are setting up the project this way?

I do not have experience with git. Maybe i do not have it installed. On some light weight Linux installations, on a VPS for example with limited disk space, installing git takes some space and my be a bit waste if one just need couple of tools (like cloudfail) and do not work with git.

**Comment by m0rtem** [comment]
Ok, that is fair enough, I will bare this in mind when I next update this project, thank you for bringing that to my attention!
