### ISSUE TITLE
File "cloudfail.py", line 277, in <module>     update()

### ISSUE THREAD

**Issue by kamoteroot** [m0rtem/CloudFail#24]
Hi Any idea on the error below? I installed it in Kali Linux 2018.1
[16:21:41] Just checking for updates, please wait...  
[16:21:41] Updating CloudFlare subnet...  
[16:21:41] Updating Crimeflare database...  
Traceback (most recent call last):
  File "cloudfail.py", line 277, in <module>
    update()
  File "cloudfail.py", line 229, in update
    zip_ref = zipfile.ZipFile("data/ipout.zip", 'r')
  File "/usr/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by sicalpath** [comment]
Me too.
Anybody know why?

**Comment by sicalpath** [comment]
Fine...
http://crimeflare.net:82/domains/ipout.zip  is   gone.

**Comment by sicalpath** [comment]
Change http://crimeflare.net:82/domains/ipout.zip to http://crimeflare.net:83/domains/ipout.zip

**Comment by m0rtem** [comment]
Hi

Thanks for bringing this to my attention, my collegue has pushed an update here: 

https://github.com/m0rtem/CloudFail/commit/1b1549a5ddbf848ed47762d77d6543a38766a598

**Comment by ehte89** [comment]
Having the same issue the domain is gone

**Comment by obnoxiousish** [comment]
hey man is crimeflare gone now?

**Comment by ehte89** [comment]
The link doesn’t work as when it tries to update the crime thing it doesn’t do anything and eventually it fails.

Thanks
