### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dangwasec** [m0rtem/CloudFail#25]
Testing for misconfigured DNS using dnsdumpster...
Traceback (most recent call last):
  File "cloudfail.py", line 285, in <module>
    dnsdumpster(args.target)
  File "cloudfail.py", line 82, in dnsdumpster
    res = DNSDumpsterAPI(False).search(target)
  File "/opt/CloudFail/DNSDumpsterAPI.py", line 80, in search
    res['dns_records']['dns'] = self.retrieve_results(tables[0])
  File "/opt/CloudFail/DNSDumpsterAPI.py", line 32, in retrieve_results
    ip = re.findall(pattern_ip, tds[1].text)[0]
IndexError: list index out of range

Have this error

**Comment by m0rtem** [comment]
Hmm interesting, have not seen this one before.

Possibly related too https://github.com/PaulSec/API-dnsdumpster.com/issues/14 ?

One thing to try is to completely remove CF and reinstall the whole thing again and see if that fixes it?

**Comment by dangwasec** [comment]
Another thing I'd like to point out:
Updating Crimeflare database... 
It took about an hour of updating, no result I thought it stopped somewhere, so I had to stop the process then after that I was able to produce the error above ^

Update: I did a reinstall and the update took 1 minute to finish. Everything works now.

**Comment by m0rtem** [comment]
Thank you very much mate for testing that. I have to be honest, I wrote the update function very quickly and most likely very late at night, it isn't great, very trivial. 

Thanks again and glad you got it working in the end.

**Comment by dhruv-kandpal** [comment]
> Another thing I'd like to point out:
> Updating Crimeflare database...
> It took about an hour of updating, no result I thought it stopped somewhere, so I had to stop the process then after that I was able to produce the error above ^
> 
> Update: I did a reinstall and the update took 1 minute to finish. Everything works now.

How did you update the crimeflare database?
