### ISSUE TITLE
Wildcard DNS

### ISSUE THREAD

**Issue by DatDraggy** [m0rtem/CloudFail#27]
It would be smarter to query *.target.xyz at the beginning and then ask the user whether they want to continue anyway or skip the dictionary test if there was a find, because the wildcard will match every single subdomain in the subdomains.txt. 
I just noticed this with my own domain since it has * on 23.78.196.226 for the lolz.

**Comment by m0rtem** [comment]
Hey Dat

Neat idea, ill bare this in mind with next release. If you wanted to branch off this and make the update youre more than welcome too also. Thanks for the help :)

**Comment by DatDraggy** [comment]
I could try when I got some time. I haven't really done much with python yet but I will try my best.
It's a pretty cool tool already though. Thanks for making it.

**Comment by m0rtem** [comment]
Thats ok I am in the same boat, real word is taking over all of my time at the moment, and I started this project to really learn python myself. Thank you though, much appreciated!
