### ISSUE TITLE
NetworkException is not defined

### ISSUE THREAD

**Issue by lstep** [m0rtem/CloudFail#3]
When running against a host that does not exist, I get an exception (tried with python2 and 3): 
```
Traceback (most recent call last):
  File "cloudfail.py", line 130, in init
    ip = socket.gethostbyname(args.target)
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cloudfail.py", line 257, in <module>
    init(args.target)
  File "cloudfail.py", line 131, in init
    except NetworkException as net_exc:
NameError: name 'NetworkException' is not defined
```

**Comment by m0rtem** [comment]
Thank you for reporting this, I have not spent much time making the code, well, beautiful as some say, so will definitely include this in next update, thanks again

**Comment by m0rtem** [comment]
@lstep can you please check if resolved in commit https://github.com/m0rtem/CloudFail/commit/0a98e6b76562ee181f80a4b65b6eb9db971a2b4d
