### ISSUE TITLE
Target is not part of cloudflare network

### ISSUE THREAD

**Issue by febc14494** [m0rtem/CloudFail#31]
Hi! 
First thanks for CF, definitely a dope tool. 

Do you know why would CF say a website is not part of Cloudflare network but I am seeing an error 1016 page from CloudFlare of said target?

Thanks a lot beforehand.

**Comment by m0rtem** [comment]
Hi there,

Thank you for your kind words!  Sorry I did not respond sooner, do you still need assistance with this?

**Comment by zombozo12** [comment]
I do, yes. I got the same problem.
