### ISSUE TITLE
Stuck at Updating Crimeflare database...

### ISSUE THREAD

**Issue by siegdolfheiler** [m0rtem/CloudFail#37]
title 
Thanks in advance

**Comment by sh1va73** [comment]
Same issue

**Comment by mayankraheja98** [comment]
any updates on this?
happening with me too..

**Comment by ringawy** [comment]
Do you fix this or what ?

**Comment by arjunis4u** [comment]
Updating Crimeflare database is keeeeep updating i mean its not moving next step hey hey you got it uh ? its stuck..plz provide fix asap

**Comment by Nash-98** [comment]
Same issue.

**Comment by Nash-98** [comment]
**You have to wait up to 5 minutes, it is not stuck. It is slow to update.**

**Comment by Nash-98** [comment]
> title
> Thanks in advance
**You have to wait up to 5 minutes, it is not stuck. It is slow to update.**

**Comment by mayankraheja98** [comment]
It worked after 18 minutes...thanks!!
