### ISSUE TITLE
The tool is dead as of now

### ISSUE THREAD

**Issue by w9w** [m0rtem/CloudFail#46]
Eternal Crimeflare database updating

**Comment by m0rtem** [comment]
tool still works i just tested. crimeflare db is 20mb file it downloads and extracts, may be due to slow internet connection? you can download file manually [here ](http://crimeflare.net:83/domains/ipout.zip) and extract into the `data` folder.

**Comment by w9w** [comment]
@m0rtem, I confirm - it seems like my VPS's internet connection was indeed slow. I just waited for some time, and it works!

![image](https://user-images.githubusercontent.com/38838852/97872344-8e62dc00-1d1e-11eb-96d2-fd9942410dba.png)
