### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by msksmail** [m0rtem/CloudFail#55]
`Testing for misconfigured DNS using dnsdumpster...  
There was an error getting results
Traceback (most recent call last):
File "/root/CloudFail/cloudfail.py", line 312, in <module>
dnsdumpster(args.target)
File "/root/CloudFail/cloudfail.py", line 86, in dnsdumpster
if res['dns_records']['host']:
TypeError: list indices must be integers or slices, not str`

**Comment by elmagnifico243** [comment]
+1, it was working 5 days ago and I don't know how this occurred.
maybe it's not connecting with the api

**Comment by thistehneisen** [comment]
For now I can only suggest commenting that line out and hoping for other options.

**Comment by m0rtem** [comment]
this should be fixed now

**Comment by laurianops** [comment]
a similar error appeared with me
