### ISSUE TITLE
Dnsdumpster problem

### ISSUE THREAD

**Issue by Al3x1S4** [m0rtem/CloudFail#58]
Hi ! 

First of all, thanks for the tool ! 

I have an issue with dnsdumpster.

There was an error getting results
Traceback (most recent call last):
  File "cloudfail.py", line 312, in <module>
    dnsdumpster(args.target)
  File "cloudfail.py", line 86, in dnsdumpster
    if res['dns_records']['host']:
TypeError: list indices must be integers or slices, not str

Would you know how to fix it ?

**Comment by m0rtem** [comment]
this should now be fixed
