### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by moxniso** [m0rtem/CloudFail#59]
[21:46:05] Testing for misconfigured DNS using dnsdumpster...
There was an error getting results
Traceback (most recent call last):
  File "cloudfail.py", line 312, in <module>
    dnsdumpster(args.target)
  File "cloudfail.py", line 86, in dnsdumpster
    if res['dns_records']['host']:
TypeError: list indices must be integers or slices, not str

I'm using Python 3.7.3

**Comment by m0rtem** [comment]
this should be fixed now

**Comment by Malashev** [comment]
> this should be fixed now

yep, it is. Thank you so much for the fast update :)

**Comment by Jotta9** [comment]
the error still continues...
