### ISSUE TITLE
python cloudfail.py --target site.com !!

### ISSUE THREAD

**Issue by roothaxor** [m0rtem/CloudFail#6]
Traceback (most recent call last):
  File "cloudfail.py", line 257, in <module>
    init(args.target)
  File "cloudfail.py", line 138, in init
    ifIpIsWithin = inCloudFlare(ip)
  File "cloudfail.py", line 150, in inCloudFlare
    isInNetwork = ip_in_subnetwork(ip,line)
  File "cloudfail.py", line 24, in ip_in_subnetwork
    (ip_integer, version1) = ip_to_integer(ip_address)
  File "cloudfail.py", line 46, in ip_to_integer
    raise ValueError("invalid IP address")
ValueError: invalid IP address

**Comment by m0rtem** [comment]
Hi thanks for reporting... is that the command you used (without !!)?

It works for me...

**Comment by truongtn** [comment]
@roothaxor Do you use python 2? 
Using python 3.4 instead

**Comment by roothaxor** [comment]
tried on both release a binary, saves time

**Comment by m0rtem** [comment]
@roothaxor but binaries take away the fun! ;-)

in relation to this issue what environment are you using? Could you share the complete log of what happens from when you type it in to when the error shows?

**Comment by roothaxor** [comment]
Window env. 
tried Cygwin still error.
executable release will be great.

**Comment by m0rtem** [comment]
ok thats cool - i have not tested on Cygwin yet I only use Linux (but have tested on some windows systems using just CMD and works fine) Ill look into this a bit later for you (plus will look into a binary release or possibly will make a SaaS application)

**Comment by roothaxor** [comment]
very well

**Comment by m0rtem** [comment]
This should now be fixed as of: f8f6761
